### ISSUE TITLE
WGP five seat shoes

### ISSUE THREAD

**Issue by Burgch** [chestertonrc/equipment#1]
**Which piece of equipment?**
WGP

**Whereabouts on it?**
Five seat shoes

**What's wrong?**
The D loops that hold the Velcro for the extendable size adjustment have come open. Hopefully just a case of squeezing them shut with some pliers.

**Photos**
Forgot to take...

 **Urgency**
Still usable, just annoying.

**Comment by southa** [comment]
Squeezed together with pliers.  Tested by rowing in them.
